# Generated by Django 5.0.6 on 2025-11-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instruments", "0005_instrumentconfig"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InstrumentConfig",
        ),
    ]
