# Generated by Django 5.0.6 on 2025-11-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_user_external_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstrumentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=100)),
                ("settings", models.JSONField(default=dict)),
            ],
        ),
    ]
