# Generated by Django 5.0.6 on 2026-03-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_instrumentconfig_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrumentconfig",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="instrument_config_samples/"
            ),
        ),
    ]
