# Generated by Django 5.0.6 on 2026-04-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_instrumentconfig_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrumentconfig",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
