# Generated by Django 5.0.6 on 2026-04-20 20:59

from django.db import migrations
defaultConfigs = [
    {
        "name": "Roland-GR-1-Trumpet",
        "settings": {},
        "file": "instrument_config_samples/Roland-GR-1-Trumpet-C5.wav",
        "user": None
    }
 ]

def update_site_forward(apps, schema_editor):
   instrument_config_model = apps.get_model("users", "InstrumentConfig")
   for config in defaultConfigs:
         instrument_config_model.objects.create(**config)

class Migration(migrations.Migration):
   
    dependencies = [
        ("users", "0014_alter_instrumentconfig_description"),
    ]

    operations = [migrations.RunPython(update_site_forward)]
