# Generated by Django 5.0.6 on 2026-04-21 01:21

from django.db import migrations

def update_site_forward(apps, schema_editor):
   instrument_config_model = apps.get_model("users", "InstrumentConfig")
   instrument_config_model.objects.filter(name="Roland-GR-1-Trumpet", user=None).update(description="Default Roland GR-1 Trumpet configuration.")
class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_auto_20260420_1659"),
    ]

    operations = [migrations.RunPython(update_site_forward)]
